<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Model" nsURI="http:///Model.ecore" nsPrefix="Model">
  <eClassifiers xsi:type="ecore:EClass" name="Exemplar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Bloqueado" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emprestimo">
    <eOperations name="gerarMulta" ordered="false" lowerBound="1"/>
    <eOperations name="DevolverExemplar" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DataEmprestimo" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DataDevolucao" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Reserva" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Professor" eSuperTypes="#//Usuario"/>
  <eClassifiers xsi:type="ecore:EClass" name="Usuario" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nome" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numRegistro" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Instituto" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ativo" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tese" eSuperTypes="#//Publicacao"/>
  <eClassifiers xsi:type="ecore:EClass" name="Publicacao">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Autor" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DataPublicacao" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Terminal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Funcionario" eSuperTypes="#//Usuario"/>
  <eClassifiers xsi:type="ecore:EClass" name="Livro" eSuperTypes="#//Publicacao"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aluno" eSuperTypes="#//Usuario"/>
  <eClassifiers xsi:type="ecore:EClass" name="Manual" eSuperTypes="#//Publicacao"/>
  <eClassifiers xsi:type="ecore:EClass" name="Periodico" eSuperTypes="#//Publicacao"/>
  <eClassifiers xsi:type="ecore:EClass" name="Biblioteca"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bibliotecario" eSuperTypes="#//Funcionario"/>
</ecore:EPackage>
